### ISSUE TITLE
Any chance of making this an npm module?

### ISSUE THREAD

**Issue by wishinghand** [maxwellito/triangulr#2]
I'd love to just easily import this as an npm module in my Vue project. I know vivus is much more popular but I honestly love this little module but I'm still figuring out how to get it working right.

**Comment by maxwellito** [comment]
Hi there,
Thanks for these kind words :)
I never thought about making an npm module from this project but I can fix
that. I hope the name is still available. If so Ill try to make it tonight.
Now you make me think I should rebuild the short documentation. Can I help
you with something?

**Comment by wishinghand** [comment]
I think my case is specific because I was using Nuxt (a server side rendered Vue framework) and I was just used to requiring NPM modules and haven't quite figured out their plugin system. 

I just tried it in a simpler HTML/CSS/JS setup and ran into a separate problem anyway, so I'll put that in a different issue.

**Comment by maxwellito** [comment]
`npm install triangulr` 👍 

Keep me posted to know if everything is working :)
