### ISSUE TITLE
this.colorRendering is not a function

### ISSUE THREAD

**Issue by wishinghand** [maxwellito/triangulr#3]
I've made a simple HTML page with only a div with an id of #myDiv. It has script tags for the Triangulr source and a custom page with code from the example in the README:

```
var mySVG = new Triangulr (600, 500, 60, 0);
document.getElementById('myDiv').appendChild(mySVG);
```

I used node-static to load on localhost. The full error text comes in as:

```
Uncaught TypeError: this.colorRendering is not a function
    at Triangulr.createTriangles (triangle.js:116)
    at new Triangulr (triangle.js:46)
    at index.js:1
```

**Comment by maxwellito** [comment]
Hi Jason,
Sorry about that. You made me realised that a method was missing. The generate color was supposed to be optional and I messed up with it :-S
It's now fixed but I recommend to use a custom method to set the color you want :)
